version: '3.7'
services:
  db_stackunderflow:
    image: mysql
    container_name: db_stackunderflow
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amt_stackunderflow
      MYSQL_USER: stackunderflow_user
      MYSQL_PASSWORD: stackunderflow_secret
    ports:
      - "3307:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  webapp_stackunderflow:
    image: amt/stackunderflow
    container_name: webapp_stackunderflow
    environment:
     - ADMIN_PASSWORD=admin
     - GAMIFICATION_ADDRESS=gamificationServer
     - GAMIFICATION_PORT=8090
     - GAMIFICATION_TOKEN=a093a78e-140b-44cb-bb86-31f0136844e9
     - UPVOTE_EVENTTYPE=1
     - NEW_QUESTION_EVENTTYPE=2
    ports:
      - "8080:8080"
    networks:
      - dev_default
      - default

networks:
  dev_default:
    external: true


